{
  "formatVersion": "1.1",
  "component": {
    "group": "de.arthurpicht",
    "module": "ap-utils-core",
    "version": "1.18.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ap-utils-core-1.18.0.jar",
          "url": "ap-utils-core-1.18.0.jar",
          "size": 27663,
          "sha512": "c381e0ccb665d0343eb67b1eb947054e76fcb62539613644599ab6ba30dcb4ea57a1ce6e5203afdf57734df665acc07eb527f6c6079dd8bcf1f1fee2202959c5",
          "sha256": "38476d68e618929eb3eed5979a1e8c4cd1c623687beec87d2dbd653027a08717",
          "sha1": "8396070872899f2b599a5067539a64dca027497a",
          "md5": "8bb6f84fd0edd3c028b44b9d9d2e9320"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ap-utils-core-1.18.0.jar",
          "url": "ap-utils-core-1.18.0.jar",
          "size": 27663,
          "sha512": "c381e0ccb665d0343eb67b1eb947054e76fcb62539613644599ab6ba30dcb4ea57a1ce6e5203afdf57734df665acc07eb527f6c6079dd8bcf1f1fee2202959c5",
          "sha256": "38476d68e618929eb3eed5979a1e8c4cd1c623687beec87d2dbd653027a08717",
          "sha1": "8396070872899f2b599a5067539a64dca027497a",
          "md5": "8bb6f84fd0edd3c028b44b9d9d2e9320"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ap-utils-core-1.18.0-javadoc.jar",
          "url": "ap-utils-core-1.18.0-javadoc.jar",
          "size": 183120,
          "sha512": "243f209693140211360e7fa6c9612928ad4da1c220b3e74731567a22c3d64cccb7c17ee93d080a248647218c9c6ebdedf48b82ea9ef2f178640f5c89f4b71ad2",
          "sha256": "3a1f7480c42e87999a62b2f07abcdd9c23979a5d51e1e399f5b3af918573430a",
          "sha1": "1ca59db6bb1b4ede8816a698e4ba12677135fae5",
          "md5": "9b669e4fba25bdf6052fee64d7c6ca25"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ap-utils-core-1.18.0-sources.jar",
          "url": "ap-utils-core-1.18.0-sources.jar",
          "size": 17385,
          "sha512": "c01d400c840a49f40c9458f55475afe4445d95f5327199892f15893d4e0f8550e16cc79ea05f92c11c3e3babf6e05c5876431bc36f9902111418ed84172d9617",
          "sha256": "2660c0b9bfe99be8f0242527f2c3d8f0ef2e58d31fb1454d676cab3822aed552",
          "sha1": "0e665c8d4973cf4ca3877258e1c58b2d29d29024",
          "md5": "2da5d68c3a9680bdc987605b4f7a3f92"
        }
      ]
    }
  ]
}
